language: cpp
sudo: required

matrix:
  include:
    - env: ARCH=x86_64 BUILD_TYPE=coverage
      addons:
        apt:
          update: true
          packages:
            - libmagic-dev
            - libjpeg-dev
            - libpng-dev
            - cimg-dev
      before_script:
        - sudo pip install gcovr
      script: travis/test-coverage.sh
      after_success: true  # also, we don't intend to upload release binaries
    - env: ARCH=i386 BUILD_TYPE=coverage
      addons:
        apt:
          update: true
          packages:
            - libmagic-dev:i386
            - libjpeg-dev:i386
            - libpng-dev:i386
            - gcc-multilib
            - g++-multilib
            - libfuse2:i386
            - libcairo2:i386
      before_script:
        - sudo pip install gcovr
      script: travis/test-coverage.sh
      after_success: true  # also, we don't intend to upload release binaries

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
