name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    strategy:
      matrix:
        ARCH: [x86_64, i386]
        BUILD_TYPE: [coverage]
      fail-fast: false

    name: ${{ matrix.BUILD_TYPE }} ${{ matrix.ARCH }}
    runs-on: ubuntu-latest

    env:
      ARCH: ${{ matrix.ARCH }}
      BUILD_TYPE: ${{ matrix.BUILD_TYPE }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install dependencies
        run: sudo pip3 install gcovr

      - name: Install multiarch dependencies
        if: matrix.ARCH == "i386"
        run: sudo apt install -y gcc-multilib g++-multilib

      - name: Test coverage
        run: bash -ex ci/test-coverage.sh
